

(*****************************)
(*     Write Propagators     *)
(*****************************)

(* Propagators in the Unitary gauge *)

FO$ScalarPropagator[field_]= I Den[p1,m]/.m-> Mass[field];

FO$GoldstonePropagator[field_,Xi_]= 0;

FO$VectorPropagatorMassless[field_,Xi_,ind_]:=-I Times@@FO$Delta@@@Transpose[{Through[ind[1]],Through[ind[2]]}](1 Den[p1,0] FO$Metric[Lor1,Lor2])/.{FF_[GG_[x_],GG_[y_]]:>FF[ ToExpression[ToString[GG]<>ToString[x]],ToExpression[ToString[GG]<>ToString[y]]]};

FO$VectorPropagatorMassive[field_,ind_]:=-I Den[p1,m] Times@@FO$Delta@@@Transpose[{Through[ind[1]],Through[ind[2]]}](FO$Metric[Lor1,Lor2]-(p1[Lor1]p1[Lor2])/m^2)/.m-> Mass[field];

FO$FermionPropagator[field_,ind_]:=(I(FO$Gamma[p1,Spin1,Spin2]+m FO$Gamma[1,Spin1,Spin2])) Den[p1,m] Times@@FO$Delta@@@Transpose[{Through[ind[1]],Through[ind[2]]}]/.{m-> Mass[field],FF_[GG_[x_],GG_[y_]]:>FF[ ToExpression[ToString[GG]<>ToString[x]],ToExpression[ToString[GG]<>ToString[y]]]};

FO$GhostPropagatorMassless[field_,ind_]:=I Den[p1,0] Times@@FO$Delta@@@Transpose[{Through[ind[1]],Through[ind[2]]}]/.{FF_[GG_[x_],GG_[y_]]:>FF[ ToExpression[ToString[GG]<>ToString[x]],ToExpression[ToString[GG]<>ToString[y]]]};

FO$GhostPropagatorMassive[field_,Xi_,ind_]:=0;



FO$Propagator[field_]:=Which[

  IndicesField=(Select[#,(Not[#===Index[Lorentz]]&&Not[#===Index[Spin]])&]&)@$IndList[field]/.{Index[GG_]:> GG};

  ScalarFieldQ[field]===True&& Not[GoldstoneQ[field]=== True]&& Not[GhostFieldQ[field]=== True],FO$ScalarPropagator[field],
  ScalarFieldQ[field]===True&& GoldstoneQ[field]=== True,FO$GoldstonePropagator[field,Xi],
  VectorFieldQ[field]===True&&Mass[field]=== 0, FO$VectorPropagatorMassless[field,Xi,IndicesField],
  VectorFieldQ[field]===True&&Not[Mass[field]===0], FO$VectorPropagatorMassive[field,IndicesField],
  FermionQ[field]===True&& Not[GhostFieldQ[field]=== True], FO$FermionPropagator[field,IndicesField],
  GhostFieldQ[field]===True&&Mass[field]=== 0, FO$GhostPropagatorMassless[field,IndicesField],
  GhostFieldQ[field]===True&&Not[Mass[field]===0], FO$GhostPropagatorMassive[field,Xi,IndicesField]

]


(*  Write propagators *)

FO$WritePropagators[out0_,allFieldsInFR_]:=Block[{out=out0,outfile,SubstitutionsPropagators,currentField,currentPropagator,SubstitutionsFieldsString,SubstitutionsPropatorsString},
  
  (* Substitutions to provide the indices that the fields should have at the propagator level  *)
  
  SubstitutionsPropagators={
  
    Field_/;(Length@$IndList[Field]<2&&ScalarFieldQ[Field]&&Not[GhostFieldQ[Field]=== True]):> Field [TagIndex[[1]],MomentumFO[[1]],LorentzIndexFO[[1]],LorentzIndexFO[[2]]],
  
    Field_/;(Length@$IndList[Field]<1&&GhostFieldQ[Field]):> Field [TagIndex[[1]],MomentumFO[[1]],LorentzIndexFO[[1]],LorentzIndexFO[[2]]],
  
    Field_/;(Length@$IndList[Field]<2&&VectorFieldQ[Field]):> Field [TagIndex[[1]],MomentumFO[[1]],LorentzIndexFO[[1]],LorentzIndexFO[[2]]],
       
    Field_/;(Length@$IndList[Field]<2&&FermionQ[Field]&&AddIndexGG[Field,1,Gluon]=== Null ):> Field [TagIndex[[1]],MomentumFO[[1]],SpinIndexFO[[1]],SpinIndexFO[[2]]],
  
    Field_/;(AddIndexGG[Field,1,Gluon]=!= Null):> Field [TagIndex[[1]],MomentumFO[[1]],LorentzIndexFO[[1]],LorentzIndexFO[[2]],AddIndexGG[Field,1,Gluon],AddIndexGG[Field,2,Gluon] ],
  
    Field_/;(AddIndexGG[Field,1,Colour]=!= Null):> Field [TagIndex[[1]],MomentumFO[[1]],SpinIndexFO[[1]],SpinIndexFO[[2]],AddIndexGG[Field,1,Colour],AddIndexGG[Field,2,Colour] ]
  };

  (* String substitutions *)
  
  SubstitutionsFieldsString = {

    ("PartTag"~~char:LetterCharacter):>"?"<>char,
    ("p"~~char:DigitCharacter):>"p"<>char<>"?",
    ("Lor"~~char:DigitCharacter):>"Lor"<>char<>"?",
    ("Spin"~~char:DigitCharacter):>"Spin"<>char<>"?",
    ("Gluon"~~char:DigitCharacter):>"Gluon"<>char<>"?",
    ("Colour"~~char:DigitCharacter):>"Colour"<>char<>"?",
    "["-> "(",
    "]"-> ")"
  };
  
  SubstitutionsPropatorsString = {

    "FO$Metric"-> "d_",
    "FO$Gamma"-> "GammaM",
    "FO$Delta"-> "d_",
    ("QuestionMark"~~char:LetterCharacter):>"?"<>char,
    "["-> "(",
    "]"-> ")"
  };


  outfile=out<>"/Propagators"<>".frm";
  
  wsp="                                                                                                                             ";
  OpenWrite[outfile];
    WriteString[outfile,"*******************************************************************\n"];
    WriteString[outfile,"* Model automalically generated by FeynRules -"<>StringTake[wsp,20]<>"*\n"];
    WriteString[outfile,"* date and time of generation : "<>StringTake[DateString[]<>wsp,34]<>"*\n"];
    WriteString[outfile,"* FeynRules model information : "<>StringTake[wsp,34]<>"*\n"];
    WriteString[outfile,"*******************************************************************\n"];
    WriteString[outfile,"\n"];
    WriteString[outfile,"\n"];
    WriteString[outfile,"*****  This file contains the Propagators   *****\n"];
    WriteString[outfile,"\n"];
    WriteString[outfile,"\n"];
    WriteString[outfile,"#procedure Propagators\n"];
    WriteString[outfile,".sort\n"];
    WriteString[outfile,"\n"];
    WriteString[outfile,"id   pro(ff?Field(x?,y?partTagInt[n],?a)) = pro(ff(x,y,?a,IntLor[n]));\n"];
    WriteString[outfile,"* id   pro(ff?Fermion(x?partTagInt[n],?a)) = pro(ff(x,partTagIntPOne[n],?a));\n"];
    WriteString[outfile,"id   pro(ff?Fermion(x?,y?partTagInt[n],p1?,iLor1?,Spin1?,Colour1?,iLor2?)) = pro(ff(x,y,p1,Spin1,IntSpin[n],Colour1,IntColour[n]));\n"];
    WriteString[outfile,"id   pro(ff?Gluoned(x?,y?partTagInt[n],p1?,iLor1?,Gluon1?,iLor2?)) = pro(ff(x,y,p1,iLor1,iLor2,Gluon1,IntGluon[n]));\n"];
    WriteString[outfile,"id   pro(ff?Gluoned(x?,y?partTagInt[n],0,iLor1?,Gluon1?,iLor2?)) = pro(ff(x,y,0,iLor1,iLor2,Gluon1,IntGluon[n]));\n"];
    WriteString[outfile,"\n"];
    WriteString[outfile,"\n"];
    WriteString[outfile,"*****  Propagators  *****\n"];
    WriteString[outfile,"\n"];
    Do[

      currentField=(StringReplace[#, SubstitutionsFieldsString ]&)@(ToString[InputForm[#] ]&)@(FieldsInFR[[j]]/.SubstitutionsPropagators);
      currentPropagator=(StringReplace[#, SubstitutionsPropatorsString ]&)@(ToString[InputForm[#] ])&@(FO$Propagator[FieldsInFR[[j]] ]//.{Complex[a_,b_]:>a+ im b});

      WriteString[outfile,"id   pro("<>currentField<>") = "<>currentPropagator<>";\n"]

    ,{j,1,Length[FieldsInFR]} ];
    WriteString[outfile,"\n"];
    WriteString[outfile,"#endprocedure Propagators\n\n"];
  Close[outfile];
  Print["done"];
]